version: 2
updates:
  - directory: /
    assignees:
      - "r17x"
    open-pull-requests-limit: 5
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: daily
    versioning-strategy: lockfile-only
    labels:
      - "automerge"
      - "dependencies"
